### ISSUE TITLE
Typo in comment

### ISSUE THREAD

**Issue by leeharr** [Matthias-Wandel/pi_blink_ip#10]
diff --git a/blink_ip.py b/blink_ip.py
index d1feea5..b0060fc 100755
--- a/blink_ip.py
+++ b/blink_ip.py
@@ -10,7 +10,7 @@
 romans = ["X","I","II","III","IV","V","VI","VII","VIII","IX"]
 #
 #  For example: 0 is blinked as (X), one long blink, 1 (I) is a short blink,
-#     4 (IX) is a short followed by a medium blink
+#     4 (IV) is a short followed by a medium blink
 #
 #  Install to run at startup with this comment:
 #      sudo blink_ip.py install

**Comment by Matthias-Wandel** [comment]
Just fixed it, change 9ff6363627b56af28390e43818df22271506dcb0

------ Original Message ------

**Comment by Matthias-Wandel** [comment]
fixed by change 9ff6363
