### ISSUE TITLE
Misleading examples

### ISSUE THREAD

**Issue by CharlesGodwin** [Matthias-Wandel/pi_blink_ip#15]
Two of the examples in the readme refer to impossible IP addresses. Each octet can only be valued 0-255.
so 192.168.2.**349** and10.10.**456.789** are impossible values.

How about 
<pre>192.168.9.149 ---- IX   I IV IX
</pre>
and
<pre>10.10.248.192 ---- II IV VIII  I IX II</pre>

**Comment by Matthias-Wandel** [comment]
Fixed by change 51ecdced782dd83a9d59fdf6b2f75d7798cf61d4

**Comment by Matthias-Wandel** [comment]
fixed in change 51ecdced782dd83a9d59fdf6b2f75d7798cf61d4
