### ISSUE TITLE
Update for Bookworm

### ISSUE THREAD

**Issue by pete4radio** [Matthias-Wandel/pi_blink_ip#16]
Appears the led0 was renamed "ACT" in bookworm: in 4 places, it should be /sys/class/leds/ACT.

**Comment by Matthias-Wandel** [comment]
fixed with change 2622f37d3468ee9d9bb0cb5f89b6ce78fb5e5ecd

**Comment by Matthias-Wandel** [comment]
fixed with change 2622f37d3468ee9d9bb0cb5f89b6ce78fb5e5ecd
