### ISSUE TITLE
ZeroConf alternative?

### ISSUE THREAD

**Issue by JasonKleban** [Matthias-Wandel/pi_blink_ip#2]
Have you read about zero-conf aka Bonjour?  I've set this up on a raspberry pi before and it allows you to ssh or http, etc, to `hostname.local` without a dns server.  Pretty easy configuration with Ubuntu image, for example, but probably any distro.

**Comment by Matthias-Wandel** [comment]
How do I use that from windows?

**Comment by JasonKleban** [comment]
I can connect to such a host from windows, no problem.  Browser or ssh from powershell or bash.

I have some links here at the beginning of a different issue I'm pursuing - but it shows a picture of an enclosure that was inspired by one of your recent builds:

https://github.com/scottlamb/moonfire-nvr/issues/87

I will review the instructions and get/find you condensed steps.  (I'm now trying to answer to multiple names on a single host, but the basic setup of a single name is really easy).

**Comment by Matthias-Wandel** [comment]
If I can connect to my pi, then I don't need it.  If I can't connect to my pi, then I don't have a linux host on the network.

**Comment by JasonKleban** [comment]
Ok - but in case I wasn't clear - You don't need a linux host (other than the one raspberry pi) for this to work and I don't think you need any special setup on Windows to find your raspberry pi from it by it's `hostname.local`.  It solves the problem of not knowing the ip address of such host with a dhcp-assigned ip address.  As soon as rpi boots and is on the same network as your windows machine, you can just ssh or browse to the rpi by name (or nslookup, i guess, if you really DO need to resolve to an ip address).

Update: I'm not a linux guru at all so I'm not 100% on this, but I do believe [this is all you'd need to add](https://www.howtoinstall.me/ubuntu/18-04/avahi-daemon/) is of course `sudo apt update` and then `sudo apt install avahi-daemon`.

It [_might_ require](https://stackoverflow.com/questions/23624525/standard-mdns-service-on-windows) that you installed iTunes at some point in the past?  Or bonjour/zeroconf/mDNS might be built into Windows at this point.  If it requires an install and if that's a deal breaker for you, my apologies - but it is so smooth that I do recommend it either way.  I happen to have Bonjour service installed from 2017 as part of iTunes, but there's some suggestion that Windows 10 supports this natively.  Hard to tease apart claims of host vs client support.

But hey, there's room in the world for both of these ways to exist!  Cool project.
