### ISSUE TITLE
Consider Applying a License

### ISSUE THREAD

**Issue by ndbeals** [Matthias-Wandel/pi_blink_ip#4]
It's such a minor thing and realistically doesn't matter, but technically your code is unlicensed and exists in a grey area that prevents companies (or anyone worried about the legal perspective) from using it.

Github has a built-in tool for searching and selecting one, try creating a new file in the project root named "LICENSE", it should activate.

**Comment by Matthias-Wandel** [comment]
Yes, I thought about it.  Done.
