### ISSUE TITLE
Not an issue, I made it too for the ESP 8266

### ISSUE THREAD

**Issue by rin67630** [Matthias-Wandel/pi_blink_ip#8]
https://github.com/rin67630/Blink-my-IP

I chose to just pulse the blinks by digit: it is not really difficult to count with and you don't need to relearn Latin numbering.

**Comment by Matthias-Wandel** [comment]
Cool!
Woudl be fun to get into the ESP32, just no time to learn the stuff, and 
with a pi zerow costing what it does, I like the idea of just logging 
into it, changing the code, and recompiling ON the actual device without 
even taking it off line.

------ Original Message ------

**Comment by rin67630** [comment]
I had it running for the ESP32, not much to change, but it took me too much time to run two versions in //
The ESP8266 is better for me it needs less energy, and has enough muscle to do the job and more...
You are free to fork it.

PS: you can change the code of an ESP application over the air, no need to take it off-line. I do it daily.
